HawtWheelzProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('members/', include('members.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('', include('home.urls')),










]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.homepage, name='homepage'),

   path('login/', views.login, name='login'),

   path('inventory/', views.inventory, name='inventory'),

   path('about/', views.about, name='about'),

   path('<int:car_id>', views.car_detail, name="car_detail")
   ]

members/urls.py
from django.urls import path
from . import views

app_name = 'members'
urlpatterns = [

    path('register/', views.register_request, name='register'),
    path('login/', views.login_request, name='login'),
    path('user/', views.user_profile, name='user_profile'),
    path('log-out/', views.logout_request, name="logout"),

]

home/models.py
import datetime
from django.db import models
from django.utils.html import mark_safe
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User


class Car(models.Model):
    # Fields
    name = models.CharField(max_length=20)
    make = models.CharField(max_length=20)
    date_added = models.DateTimeField('date added')
    model = models.CharField(max_length=20)
    color = models.CharField(max_length=20, default='color')
    year = models.IntegerField(default=0)
    # Images require Pillow 9.0
    image = models.ImageField(upload_to='home/images', default='home/images/empty-default.jpg')
    image1 = models.ImageField(upload_to='home/images', default='home/images/empty-default.jpg')
    image2 = models.ImageField(upload_to='home/images', default='home/images/empty-default.jpg')
    image3 = models.ImageField(upload_to='home/images', default='home/images/empty-default.jpg')
    image4 = models.ImageField(upload_to='home/images', default='home/images/empty-default.jpg')
    price = models.IntegerField(default=0)
    description = models.CharField(max_length=500, default='des')

    def __str__(self):
        return self.name

    def was_added_recently(self):  # will return true if the car was added in the last week
        now = timezone.now()
        return now - datetime.timedelta(days=7) <= self.date_added <= now

    def get_detail(self):  # will return car info needed for the detail html
        return reverse('car_detail', kwargs={
            'car_id': self.id
        })


class Profile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    wishlist = models.ManyToManyField(Car)

    def __str__(self):
        return f'{self.owner.email} Profile'

home/forms.py
from .models import Profile
from django import forms
from .models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('wishlist',)

home/views.py
from django.shortcuts import render, get_object_or_404
from .models import Car
from .filters import CarFilter


def homepage(request):
    new_cars = Car.objects.order_by('-date_added')[:6]
    best_deal = Car.objects.order_by('price')[:6]
    data = {'new_cars': new_cars,
            'best_deal': best_deal
            }

    return render(request, 'home/index.html', data)


def inventory(request):
    # this holds all cars in the database

    car_list = Car.objects.all()
    car_filter = CarFilter(request.GET, queryset=car_list)
    car_list = car_filter.qs

    context = {
        'car_list': car_list, 'car_filter': car_filter
    }
    # context contains all data sent
    return render(request, 'home/inventory.html', context)


def search_results_view(request):
    if request.method == "get":
        car_list = Car.objects.all()
        car_filter = CarFilter(request.GET, queryset=car_list)
        car_list = car_filter.qs
        context = {
            'car_list': car_list, 'car_filter': car_filter
        }
        return render(request, 'home/inventory.html', context)
    else:
        car_list = Car.objects.all()

        return render(request, 'home/inventory.html', {'car_list': car_list})


def about(request):
    return render(request, 'home/about.html')


def login(request):
    return render(request, 'home/login.html')


def car_detail(request, car_id):
    cars = get_object_or_404(Car, id=car_id)
    if request.method == "POST":
        cars = Car.objects.get(id=car_id)
        request.user.profile.wishlist.add(cars)
        return render(request, 'members/wish.html')

    context = {
        'cars': cars
    }
    return render(request, 'home/detail.html', context)

templates/home/about.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}

  <div class="container-fluid" style ="background: radial-gradient(circle, rgba(111,126,133,1) 0%, rgba(13,17,22,1) 100%);
   background-size: cover; overflow-x: hidden;position: relative; ">
    <div class="row justify-content-center">
      <div class="text-center">


             <h1 class ="text-white display-1">About Us</h1>
          <p class="fw-bold text-white-50 lead" style="font-size: x-large">
              HyperWheelz was founded by Ezequiel Hernandez in 2022.
              It all started when Professor Jennifer Jin assigned the engineers to group four on one fateful day. </p>
      <p class="lh-1 text-white lead" style="font-size: larger">One man's vision to create the best car dealership with the fairest prices for electric cars.
          Along the way they utilized the lessons that they learned from CSE 4550. They built a business using team management,
          hard work, and first-hand experience with html, css, django, and GitHub. It was quite a journey for these engineers.
          HyperWheelz will become a household name for all CSUSB students as gas prices raise and students go broke. Electric
          cars will be the car the future. By Spring 2022 we hope to provide the best user experience in the city of San Bernardino. </p>

      </div>
    </div>

        <div class ="container-fluid" style="background-color: grey; width: 100%">
            <div class = "row">
                <div class = "col-xl-6 col-lg-6 col-md-6">
        <img src = "../../static/home/images/dealer.jpg" alt ="..." style ="width: 106%; height: 100%; margin-left: -10px">
                </div>
                <div class = "col-xl-6 col-lg-6 col-md-6" style = "padding-left: 20px">
    <h1 class ="text-center text-black-50 display-2">Background</h1>
<h6 class="fw-bold text-center text-white display-6"> Why choose us? </h6>
            <div class ="text-white" style="font-size: larger">
   <p class=" text-center lead">We offer the best deals on electric cars along with student discounts for coyote students.
       GO COYOTES! Since gas cost an arm and a leg these days, electric cars will be more cost-efficient. According to Feilding Cage,
       The long road to electric cars, “Less than 1% of the 250 million cars, SUVs and light-duty trucks on the road in the
       United States are electric.” Looking at the IHS Markit industry analysis of 45% of cars sales could be electric by 2035.
       Our company is 13 years ahead of everyone else.</p>
                <br>
                <div style ="text-align: center">
                    <div class ="lead">
<p class="lh-1">-We have one semester of experience</p>
    <p class="lh-1">-Award-winning service </p>
    <p class="lh-1">-No hidden cost</p>
    <p class="lh-1">-Different make, model, and prices </p>
                    </div>
            </div>
            </div>
        </div>
        </div>
        </div>

        <br>

         <div class="container-fluid" style ="background: gray">
            <div class ="row">
                <div class = "col-xl-6 col-lg-6 col-md-6 align-content-center">
                    <h1 class="text-center text-black-50 display-2"> Features</h1>
      <div class ="text-white" style ="text-align: center; font-size: large">
            <p class="lh-1 lead">- Can be used on mobile and any web browser</p>
      <p class="lh-1 lead">- Create an account</p>
      <p class="lh-1 lead">- Login page</p>
    <p class="lh-1 lead">- Favorites and Details page</p>
    <h1 class="text-center text-black-50 display-2"> HyperWheelz Mission </h1>
              <div class ="text-white" style ="text-align: center; font-size: large">
    <p class="lh-lg lead">*We will respect your time.</p>
     <p class="lh-lg lead">*We will market our products and services honestly.</p>
     <p class="lh-lg lead">*We will employ a professional, well-trained and knowledgeable staff.</p>
     <p class="lh-lg lead">*We will offer only products and services that meet your needs</p>
     <p class="lh-lg lead">*We will provide clear explanations of all pricing and paperwork.</p>
     <p class="lh-lg lead">*We will deliver your vehicle clean with a full explanation of features.</p>
                </div>
      </div>
                </div>
                    <div class = "col-xl-6 col-lg-6 col-md-6">
          <img src = "../../static/home/images/store.jpg" alt ="..."
             style = "width: 107%; height: 100%; margin-left: -13px">
      </div>
        </div>
        </div>
      <div style ="font-size: large">
        <p class="fw-bold text-center text-black display-3">New Arrivals </p>
   <p class="lh-sm text-center text-white lead mb-0" style="font-size: x-large">For anyone looking for the latest and greatest car experience, our new electric
       inventory boasts an extensive selection of excellent models including... We offer exclusive savings for college graduates
       and CS majors.</p>
     <p class="fw-bold text-center text-black display-3">Used cars, Trucks, and SUVS </p>
     <p class="lh-sm text-center text-white lead" style="font-size: x-large">If you're on a budget we have a lineup of used cars, from the average everyday
         hybrid to a luxury vehicle. They are quality-assured certified pre-owned models to satisfy all your needs. </p>
    <p class="fw-bold"> </p>
 <p class="lh-sm"></p>
    <p class="lh-lg"></p>
      </div>
  </div>
    <br>
    <h1 class ="text-center" style =""><b>FAQs?</b></h1>
<div class="accordion " id="accordionExample">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                Why choose Hyper Wheelz?
      </button>
    </h2>
    <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
      <div class="accordion-body">
          We as a dealership decided to be different from other car dealerships by focusing primarily on electric vehicles
          which have become the latest trend in transportation.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
       Why choose to sell only electric vehicles?
      </button>
    </h2>
    <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
      <div class="accordion-body">
    At Hyper Wheelz we decided to focus on electric cars to lower car emissions from gas powered vehicles. As we try to lower
          as much car emission as possible by switching over to the clean power of electricity.
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
        Can I charge my vehicle at home?
      </button>
    </h2>
    <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
      <div class="accordion-body">
    Yes, what's so convenient about electric cars is you can simply plug them in back home and let it charge. No longer having the hassle of
          driving to a nearby gas station anymore.
      </div>
    </div>
  </div>
<div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
        Is there new vehicles being added?
      </button>
    </h2>
    <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour" data-bs-parent="#accordionExample">
      <div class="accordion-body">
    Yes, our dealership is always adding new vehicles, so you can shop your favorite models at low prices you can afford.
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/home/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
{% include 'home/head.html' %}
</head>

<body  >
  {% include 'home/navbar.html' %}
  {% include 'home/messages.html' %}
  {% block content %}
  {% endblock content %}
  {% include 'home/footer.html' %}

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script src="https://apis.google.com/js/platform.js" async defer></script>

</body>


</html>

templates/home/carousel.html
{% load static %}



{#This styles the elements inside the carousel to have consistent height#}
{#    <style>#}
{#      #indexCarousel .carousel-item img{#}
{#          object-fit: cover;#}
{#          object-position: center;#}
{#          height: 80vh;#}
{#          overflow: hidden;#}
{##}
{#      }#}
{#    </style>#}

       <div id="indexCarousel" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-indicators">
            <button type="button" data-bs-target="#indexCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#indexCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#indexCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
          </div>
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="4000" >
              <img class="d-block w-100 " src="{% static 'home/images/Carousel hummer.jpeg' %}">
              <div class="carousel-caption p-2 rounded-3" style="background: rgba(0,0,0,0.51)">
                    <h5>NEW!! 2022 HUMMER EV</h5>
                    <p>POWER THROUGH ANY OBSTACLE.</p>
              </div>
            </div>
            <div class="carousel-item " data-bs-interval="4000" >
              <img class="d-block w-100" src="{% static 'home/images/Carousel 2022-chevy-silverado-25.jpg' %}">
              <div class="carousel-caption p-2 rounded-3" style="background: rgba(0,0,0,0.51)">
                <h5>NEW!! 2022 CHEVROLET SILVERADO EV</h5>
                <p>ALL AMERICAN WORK TRUCK.</p>
              </div>
            </div>
            <div class="carousel-item" data-bs-interval="4000">
              <img class="d-block w-100 " src="{% static 'home/images/Carousel Porsche-EV2.jpg' %}">
              <div class="carousel-caption p-2 rounded-3" style="background: rgba(0,0,0,0.51)">
                <h5>NEW!! 2022 PORSCHE EV</h5>
                <p>EXPERIENCE HYPER SPEED WITH THE NEW 2022 Porsche EV.</p>
              </div>
            </div>
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#indexCarousel" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#indexCarousel" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
       </div>

templates/home/detail.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}



   <div class = "carousel">
        <img src="{% static 'home/images/wheel1.png' %}" width ="100%" height="400px" alt="..." style = "background-attachment: fixed;
        background-position: center;background-size: cover">

        <div class = "container-fluid text-white text-center opacity-50"
             style = "background-color: black; width: 100%; position: absolute; bottom: 0;left: 0;right: 0"> {# The text overlay for the image itself along with the text underneath #}
            <h1 style = " font-style: italic;text-align: left" class ="display-1">Specs</h1>
        </div>
    </div>

  <div class="row ">
        <h1 class="display-2 "> {{ cars.name}}</h1>
  </div>



<div class="card mb-3" >
  <div class="row g-0">
    <div class="col-md-8">
     <div class="container">
<div id="carouselExampleFade" class="carousel slide carousel-fade rounded-3" data-bs-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{ cars.image.url }}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{ cars.image1.url }}" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="{{ cars.image2.url }}" class="d-block w-100" alt="...">
    </div>
      <div class="carousel-item">
      <img src="{{ cars.image3.url }}" class="d-block w-100" alt="...">
    </div>
      <div class="carousel-item">
      <img src="{{ cars.image4.url }}" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>
    </div>
    <div class="col-md-4">
      <div class="card-body">
        <h2 class="card-title">Price:</h2>
        <p class="card-text">{{ cars.price }}</p>
          <h2 class="card-title">Make:</h2>
        <p class="card-text">{{ cars.make }}</p>
          <h2 class="card-title">Year:</h2>
        <p class="card-text">{{ cars.year }}</p>
          <h2 class="card-title">Model:</h2>
        <p class="card-text">{{ cars.model }}</p>
          <h2 class="card-title">Type:</h2>
        <p class="card-text">{{ cars.type }}</p>
          <h2 class="card-title">Color:</h2>
        <p class="card-text">{{ cars.color }}</p>
          <h2 class="card-title">Description:</h2>
        <p class="card-text">{{ cars.description }}</p>
         {% if user.is_authenticated %}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" value="{{self.id}}" name="product_pk">
                <div class="col-md-12 text-center">
                    <button type="submit" class="btn btn-outline-secondary" >Add to Favorites</button>
                        </div>
                    </form>
               {% else %}
             <div class="col-md-12 text-center">
                     <a href="members/login" class="btn btn-outline-secondary" >Add to Favorites</a>
             </div>
        {% endif %}
        <p class="card-text"><small class="text-muted">Vehicle became available on {{ cars.date_added }}</small></p>
      </div>
    </div>
  </div>
</div>




{# end of column #}
{% endblock content %}

templates/home/footer.html
{% load static %}


<footer style="background-color: rgb(0,0,0);padding-bottom: 3%;" id="footer">
    <h3 style="color: white; text-align: center; font-size: 36px;padding-top: 3%;padding-bottom: 3%">Come Visit Us!</h3>
<!---Left column of footer text-->
  <div style="text-align: left;float: left; font-size: 17px; color: white;padding-left:15%;padding-right: 5%">
        <p style="font-weight: bolder; text-decoration: underline">LOCATION:</p>
            <p>5500 University Pkwy, San Bernardino, CA 92407</p>
        <p style="font-weight: bolder; text-decoration: underline">Contact: </p>
            <p>(909) 479-5482</p>
        <p style="font-weight: bolder; text-decoration: underline">Hours: </p>
            <p>Monday - Friday: 9AM - 6PM</p>
            <p>Saturday - Sunday: 10AM - 4PM</p>
        <p style="font-weight: bolder; text-decoration: underline">EMAIL:</p>
            <p>sales@hyperwheelz.com</p>
    </div>
<!---Right column of footer containing google map-->
<iframe style="padding-left:10%" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d886.9411089463574!2d-117.32377563919349!3d34.181247593664935!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c3519b1645c8d7%3A0xfac142d2f0f47922!2sCalifornia%20State%20University%2C%20San%20Bernardino!5e0!3m2!1sen!2sus!4v1647213948106!5m2!1sen!2sus" width="500" height="350"></iframe>

 <!---Copyright tag-->
<p style="color: white; text-align: center; font-size: 18px;padding-top: 20px;">USA, Hyper Wheelz Dealership.- Copyright 2022©</p>
</footer>

templates/home/head.html
{% load static %}
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="google-signin-client_id" content="1024560547050-mg06ol482dsgl4jv3t5n8osl2qj6ikev.apps.googleusercontent.com">
<!-- Meta description changes from page to page(used by search engines to describe content)
//<meta name="description" content="This is a description of the content on page (120 char)">-->

 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

templates/home/login.html
{% load socialaccount %}


<head>
    <title>Google Registration</title>
</head>

<body>
    <h1>My Google Login Project</h1>
    {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }} !</p>

    {% else %}
    <h1>My Google Login Project</h1>
{#        <div class="g-signin2" data-onsuccess="onSignIn"></div>#}
    <a href="{% provider_login_url 'google' %}">Login with Google</a>
    {% endif %}

</body>

templates/home/messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

templates/home/navbar.html
{% load static %}
{% include 'home/head.html'%}


<div class = "container-lg text-center">
        <header style="background: white">
            <img src="{% static 'home/images/HyperWheelsLogo.svg'%}" alt="logo" style=";height: 105px;">
        </header>
</div>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
    <!--small logo on navbar-->
        <a class="navbar-brand p-1" href="#">
            <img src="{% static 'home/images/logo1.6.svg'%}"
                 class="d-inline-block align-top"
                 alt="logo" style="width: 50px;height: 50px">
        </a>

         <div class="justify-content-md-end">
             <button class="navbar-toggler " type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
             <button type="button" class="btn btn-outline-secondary" data-bs-toggle="modal" data-bs-target="#loginModal">Sign In</button>
         </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-sm-0 nav-fill w-100">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'homepage' %}" >Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'inventory' %}">Inventory</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Cars</a></li>
                  <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Compact</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">SUVs</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
          </ul>
        </div>
{% comment %}
        <form class="d-flex">
            <div >
                <label><input id ="my-input" type="text" class="form-control me-2 active"></label>
                <div class="float-end">
                    <button type="submit" class="btn btn-outline-secondary  align-content-sm-center active">Search</button>
                </div>
            </div>
        </form>
{% endcomment %}
      </div>
    </nav>


{#--Login Modal--#}

<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">

          <div class="container">
              <div class="row">
                  <h5 class="modal-title" id="exampleModalLabel">Please Login to Continue</h5>
                  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
          </div>
      </div>
      <div class="modal-body">
        <div class=" row">
{% if user.is_authenticated %}

      <li class="nav-item">
        <a class="nav-link" href="/members/log-out">Logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Welcome, {{user.username}}</a>
      </li>
      {% else %}
            <div class ="d-grid gap-2">
                <div class="col-md-12 text-center">
                     <a href="{% url 'members:login' %}" class="btn btn-outline-secondary" >Login</a>
                </div>
                <div class="col-md-12 text-center">
                     <a href="{% url 'members:register' %}" class="btn btn-outline-secondary" >Register</a>
                </div>

            </div>
        {% endif %}
        </div>





      </div>
      <div class="modal-footer">

      </div>
    </div>
  </div>
</div>